/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmEmail: typeof import('./src/components/ConfirmEmail.vue')['default']
    Dashboard: typeof import('./src/components/pages/dashboard.vue')['default']
    EditProfile: typeof import('./src/components/EditProfile.vue')['default']
    ElectionFederal: typeof import('./src/components/ElectionFederal.vue')['default']
    ElectionLocal: typeof import('./src/components/ElectionLocal.vue')['default']
    Elections: typeof import('./src/components/Elections.vue')['default']
    ElectionState: typeof import('./src/components/ElectionState.vue')['default']
    Footer: typeof import('./src/components/Footers/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LoginVoters: typeof import('./src/components/LoginVoters.vue')['default']
    ManageVotersCrud: typeof import('./src/components/ManageVotersCrud.vue')['default']
    NavMain: typeof import('./src/components/Navs/NavMain.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RegisterVoters: typeof import('./src/components/RegisterVoters.vue')['default']
    Reports: typeof import('./src/components/Reports.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signup: typeof import('./src/components/Signup.vue')['default']
    SingleTraining: typeof import('./src/components/SingleTraining.vue')['default']
    Todos: typeof import('./src/components/Todos.vue')['default']
    UploadDocument: typeof import('./src/components/UploadDocument.vue')['default']
  }
}
