/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Clean': RouteRecordInfo<'/Clean', '/Clean', Record<never, never>, Record<never, never>>,
    '/ConfirmEmail': RouteRecordInfo<'/ConfirmEmail', '/ConfirmEmail', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/EditProfile': RouteRecordInfo<'/EditProfile', '/EditProfile', Record<never, never>, Record<never, never>>,
    '/ElectionFederal': RouteRecordInfo<'/ElectionFederal', '/ElectionFederal', Record<never, never>, Record<never, never>>,
    '/ElectionLocal': RouteRecordInfo<'/ElectionLocal', '/ElectionLocal', Record<never, never>, Record<never, never>>,
    '/Elections': RouteRecordInfo<'/Elections', '/Elections', Record<never, never>, Record<never, never>>,
    '/ElectionState': RouteRecordInfo<'/ElectionState', '/ElectionState', Record<never, never>, Record<never, never>>,
    '/LoginVoters': RouteRecordInfo<'/LoginVoters', '/LoginVoters', Record<never, never>, Record<never, never>>,
    '/ManageAuthors': RouteRecordInfo<'/ManageAuthors', '/ManageAuthors', Record<never, never>, Record<never, never>>,
    '/ManageCountries': RouteRecordInfo<'/ManageCountries', '/ManageCountries', Record<never, never>, Record<never, never>>,
    '/ManageUsers': RouteRecordInfo<'/ManageUsers', '/ManageUsers', Record<never, never>, Record<never, never>>,
    '/Profile': RouteRecordInfo<'/Profile', '/Profile', Record<never, never>, Record<never, never>>,
    '/RegisterVoters': RouteRecordInfo<'/RegisterVoters', '/RegisterVoters', Record<never, never>, Record<never, never>>,
    '/Reports': RouteRecordInfo<'/Reports', '/Reports', Record<never, never>, Record<never, never>>,
    '/S3Upload': RouteRecordInfo<'/S3Upload', '/S3Upload', Record<never, never>, Record<never, never>>,
    '/Signup': RouteRecordInfo<'/Signup', '/Signup', Record<never, never>, Record<never, never>>,
    '/UploadDocument': RouteRecordInfo<'/UploadDocument', '/UploadDocument', Record<never, never>, Record<never, never>>,
  }
}
